apiVersion: v1
kind: PersistentVolume
metadata:
  name: caddy-data
spec:
  hostPath:
    path: /var/lib/cluster-data/caddy
    type: DirectoryOrCreate
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: caddy-data-claim
  namespace: default
spec:
  storageClassName: ""
  volumeName: caddy-data
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
