apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: linkding
  namespace: default
spec:
  secretName: linkding-psquid-net-tls
  dnsNames:
  - linkding.psquid.net
  issuerRef:
    name: digitalocean-dns
    kind: ClusterIssuer
