apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: psquid-net
  namespace: default
spec:
  secretName: psquid-net-tls
  dnsNames:
  - psquid.net
  - "*.psquid.net"
  issuerRef:
    name: digitalocean-dns
    kind: ClusterIssuer
