apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: digitalocean-dns
spec:
  acme:
    email: letsencrypt@psquid.net
    server: https://acme-v02.api.letsencrypt.org./directory
    privateKeySecretRef:
      name: letsencrypt-acme
      key: privateKey
    solvers:
    - dns01:
        digitalocean:
          tokenSecretRef:
            name: digitalocean-dns
            key: access-token
