apiVersion: apps/v1
kind: Deployment
metadata:
  name: linkding
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: linkding
  template:
    metadata:
      labels:
        app: linkding
    spec:
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: linkding-data-claim
      containers:
      - name: app
        image: sissbruecker/linkding:latest@sha256:0c0a9a04c7ebd644293c37f98710872fe7cdff0ea1ff7fd9be4d235e4c4678d2
        volumeMounts:
        - name: data
          mountPath: /etc/linkding/data
        ports:
        - containerPort: 9090
