apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - operator.yaml
patches:  # patch out the upstream yaml's empty secret - will be created out of band
  - patch: |
      apiVersion: v1
      kind: Secret
      metadata:
        name: operator-oauth
        namespace: tailscale
      $patch: delete
  - patch: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: operator
        namespace: tailscale
      spec:
        template:
          spec:
            containers:
              - name: operator
                env:
                - name: APISERVER_PROXY
                  value: "true"
                  $patch: replace
