apiVersion: v1
kind: PersistentVolume
metadata:
  name: navidrome-data
spec:
  hostPath:
    path: /var/lib/cluster-data/navidrome
    type: DirectoryOrCreate
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: navidrome-data-claim
  namespace: default
spec:
  storageClassName: ""
  volumeName: navidrome-data
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
