apiVersion: apps/v1
kind: Deployment
metadata:
  name: immich
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: immich
  template:
    metadata:
      labels:
        app: immich
    spec:
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: immich-data-claim
      - name: shm
        emptyDir:
          medium: Memory
          sizeLimit: 128Mi
      securityContext:
        runAsUser: 3822
        runAsGroup: 3822
      containers:
      - name: app
        image: ghcr.io/immich-app/immich-server:v3@sha256:b434cb9287eea1471c9974845914d4dd328c9c2d652e446ed4930f99944f0ceb
        env:
        - name: TZ
          value: "Etc/UTC"
        - name: IMMICH_VERSION
          value: v3
        - name: IMMICH_LOG_LEVEL
          value: warn
        - name: IMMICH_MACHINE_LEARNING_URL
          value: "false"
        - name: REDIS_HOSTNAME
          value: localhost
        - name: DB_HOSTNAME
          value: localhost
        - name: DB_DATABASE_NAME
          value: immich
        - name: DB_USERNAME
          value: postgres
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: immich
              key: POSTGRES_PASSWORD
        volumeMounts:
        - name: data
          mountPath: /data
          subPath: library
        ports:
        - containerPort: 2283
      - name: db
        image: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0@sha256:bcf63357191b76a916ae5eb93464d65c07511da41e3bf7a8416db519b40b1c23
        env:
        - name: POSTGRES_INITDB_ARGS
          value: "--data-checksums"
        - name: POSTGRES_DB
          value: immich
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: immich
              key: POSTGRES_PASSWORD
        volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql/data
          subPath: database
        - name: shm
          mountPath: /dev/shm
      - name: redis
        image: valkey/valkey:9@sha256:a91d34ab33975b1054e26f1bd9995b268f7e0c507b5ded7f3d181a1a25521630
