apiVersion: apps/v1
kind: Deployment
metadata:
  name: miniflux
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: miniflux
  template:
    metadata:
      labels:
        app: miniflux
    spec:
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: miniflux-data-claim
      securityContext:
        runAsUser: 8080
        runAsGroup: 8080
      containers:
      - name: app
        image: ghcr.io/miniflux/miniflux:latest@sha256:49d7b60987616387c306a8023087b31f2c9b7b21288b523026cb04058e8b6dbb
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: miniflux
              key: DATABASE_URL
        envFrom:
        - configMapRef:
            name: miniflux
        ports:
        - containerPort: 8080
        startupProbe:
          httpGet:
            path: /liveness
            port: 8080
          failureThreshold: 12  # 12 * 10s = 2 minutes startup leeway
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /liveness
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /readiness
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 30
      - name: db
        image: postgres:18@sha256:4ef4dbc939d61acea57712655ddb4b4ab27419c913f94cca0cd57cb3ea3c2280
        env:
        - name: POSTGRES_DB
          value: miniflux
        - name: POSTGRES_USER
          value: miniflux
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: miniflux
              key: POSTGRES_PASSWORD
        volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql
