apiVersion: apps/v1
kind: Deployment
metadata:
  name: forgejo
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: forgejo
  template:
    metadata:
      labels:
        app: forgejo
    spec:
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: forgejo-data-claim
      containers:
      - name: app
        image: codeberg.org/forgejo/forgejo:16@sha256:7c4e1db440be7b2ca685b49d0d7864cdd78e92431f531bf7893659def8200fc5
        env:
        - name: USER_UID
          value: "1000"
        - name: USER_GID
          value: "1000"
        - name: TZ
          value: "Europe/London"
        - name: FORGEJO__database__DB_TYPE
          value: postgres
        - name: FORGEJO__database__HOST
          value: "localhost:5432"
        - name: FORGEJO__database__NAME
          value: forgejo
        - name: FORGEJO__database__USER
          value: forgejo
        - name: FORGEJO__database__PASSWD
          valueFrom:
            secretKeyRef:
              name: forgejo
              key: POSTGRES_PASSWORD
        volumeMounts:
        - name: data
          mountPath: /data
          subPath: data
        ports:
        - containerPort: 30022
        - containerPort: 3000
      - name: db
        image: postgres:18@sha256:4ef4dbc939d61acea57712655ddb4b4ab27419c913f94cca0cd57cb3ea3c2280
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
        env:
        - name: POSTGRES_DB
          value: forgejo
        - name: POSTGRES_USER
          value: forgejo
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: forgejo
              key: POSTGRES_PASSWORD
        volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql/data
          subPath: database
