apiVersion: apps/v1
kind: Deployment
metadata:
  name: forgejo
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: forgejo
  template:
    metadata:
      labels:
        app: forgejo
    spec:
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: forgejo-data-claim
      containers:
      - name: app
        image: codeberg.org/forgejo/forgejo:16@sha256:cf5f5ae6acf2ababca0ee3d255705b83a47f35b25e07fc931d694d60664053fe
        env:
        - name: USER_UID
          value: "1000"
        - name: USER_GID
          value: "1000"
        - name: TZ
          value: "Europe/London"
        - name: FORGEJO__database__DB_TYPE
          value: postgres
        - name: FORGEJO__database__HOST
          value: "localhost:5432"
        - name: FORGEJO__database__NAME
          value: forgejo
        - name: FORGEJO__database__USER
          value: forgejo
        - name: FORGEJO__database__PASSWD
          valueFrom:
            secretKeyRef:
              name: forgejo
              key: POSTGRES_PASSWORD
        - name: FORGEJO__session__PROVIDER
          value: redis
        - name: FORGEJO__session__PROVIDER_CONFIG
          value: "redis://localhost:6379/1"
        - name: FORGEJO__cache__ADAPTER
          value: redis
        - name: FORGEJO__cache__HOST
          value: "redis://localhost:6379/2"
        - name: FORGEJO__cache__ITEM_TTL
          value: "16h"
        - name: FORGEJO__queue__TYPE
          value: redis
        - name: FORGEJO__queue__CONN_STR
          value: "redis://localhost:6379/3"
        volumeMounts:
        - name: data
          mountPath: /data
          subPath: data
        ports:
        - containerPort: 30022
        - containerPort: 3000
        startupProbe:
          httpGet:
            path: /api/healthz
            port: 3000
          failureThreshold: 12  # 12 * 10s = 2 minutes startup leeway
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/healthz
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 30
      - name: db
        image: postgres:18@sha256:5a5a84b19854a9ffaa54082c166ff4ec27473a361e496e5ea167f298f2da9722
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
        env:
        - name: POSTGRES_DB
          value: forgejo
        - name: POSTGRES_USER
          value: forgejo
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: forgejo
              key: POSTGRES_PASSWORD
        volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql
          subPath: database
      - name: redis
        image: valkey/valkey:9@sha256:418652cfb58ef879d4978c33553735d7147016032d5aefaa14c828e611eb9dfd
