apiVersion: apps/v1
kind: Deployment
metadata:
  name: homeassistant
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homeassistant
  template:
    metadata:
      labels:
        app: homeassistant
    spec:
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: homeassistant-data-claim
      securityContext:
        runAsUser: 3218
        runAsGroup: 3218
      containers:
      - name: app
        image: ghcr.io/home-assistant/home-assistant:stable@sha256:a1bc133af84ee6505fe2c266d9805b7c75b780dfdc188edfee3b11e8f3cd8efe
        env:
        - name: TZ
          value: "Europe/London"
        volumeMounts:
        - name: data
          mountPath: /config
        ports:
        - containerPort: 8123
