apiVersion: apps/v1
kind: Deployment
metadata:
  name: homeassistant
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homeassistant
  template:
    metadata:
      labels:
        app: homeassistant
    spec:
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: homeassistant-data-claim
      securityContext:
        runAsUser: 3218
        runAsGroup: 3218
      containers:
      - name: app
        image: ghcr.io/home-assistant/home-assistant:stable@sha256:612d76760b544cb40b7ba01387fdac964c59a6a550a50a4d30b4773c822d2918
        env:
        - name: TZ
          value: "Europe/London"
        volumeMounts:
        - name: data
          mountPath: /config
        ports:
        - containerPort: 8123
