apiVersion: apps/v1
kind: Deployment
metadata:
  name: homeassistant
  namespace: default
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: homeassistant
  template:
    metadata:
      labels:
        app: homeassistant
    spec:
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: homeassistant-data-claim
      securityContext:
        runAsUser: 3218
        runAsGroup: 3218
      containers:
      - name: app
        image: ghcr.io/home-assistant/home-assistant:stable@sha256:3e6710a7ab2a61311d9d899b719f6c3657791c63e8f4942cec4ebc42401d6b76
        env:
        - name: TZ
          value: "Europe/London"
        volumeMounts:
        - name: data
          mountPath: /config
        ports:
        - containerPort: 8123
        startupProbe:
          httpGet:
            path: /
            port: 8123
          failureThreshold: 12  # 12 * 10s = 2 minutes startup leeway
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 8123
          initialDelaySeconds: 10
          periodSeconds: 30
