apiVersion: apps/v1
kind: Deployment
metadata:
  name: kavita
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kavita
  template:
    metadata:
      labels:
        app: kavita
    spec:
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: kavita-data-claim
      securityContext:
        runAsUser: 1993
        runAsGroup: 1993
      containers:
      - name: app
        image: ghcr.io/kareadita/kavita:latest@sha256:454f2a77ac740b70c58cc7300a11122fc9ce7b7e2161ef5b0d1df8f81067cc85
        env:
        - name: TZ
          value: "Europe/London"
        volumeMounts:
        - name: data
          mountPath: /kavita/config
          subPath: config
        - name: data
          mountPath: /library
          subPath: library
        ports:
        - containerPort: 5000
