apiVersion: v1
kind: PersistentVolume
metadata:
  name: backup-data
spec:
  hostPath:
    path: /var/lib/cluster-data
    type: Directory
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 200Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backup-data-claim
  namespace: default
spec:
  storageClassName: ""
  volumeName: backup-data
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
